version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_crud
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/db.sqlite
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    depends_on:
      - api
